### ISSUE TITLE
タイムスケジュール作成

### ISSUE THREAD

**Issue by denari** [kosen10s/lt04docs#3]
**本当に毎回恒例の奴でいいのか**

**Comment by pndcat** [comment]
人数見て考えてもいいかもね。
例えば初参加者が多いんだったら、古参者は本当に1人1スライドの約1分ぐらいにしておいて、先にpdf集めて時短☆みたいなことするのもありかと（パソコン変えるのもだるいんだったらね）

今回は会場をお金払って借りるから、いつもよりは時間気をつけたほうがいいのかなとかいう懸念も。

**Comment by denari** [comment]
なるほど、では、とりあえずこの件は「#3と大体同じ段取りでの進行」を行うつもりで「一旦」進行して、参加者の層と人数を確認した後にもう一度取り上げる感じにしよう。

```
余談なんだけど、こういう場合はissueを「残す」ものなのだろうか、
それとも「一旦」の時点でissueを消して、再度取り上げるときにissueを「再度作る」ものなのだろうか。
残すほうが自然だと思っているのは僕だけか...??
```

**Comment by c-bata** [comment]
> 余談なんだけど、こういう場合はissueを「残す」ものなのだろうか、
> それとも「一旦」の時点でissueを消して、再度取り上げるときにissueを「再度作る」ものなのだろうか。
> 残すほうが自然だと思っているのは僕だけか...??

今更だけど、閉じると忘れちゃうからIssueの一覧にはあったほうがいいと思う。
ラベルで `in progress` とかつけて分類するのをよく見かけるかな。ただいまだとIssueの数10個ぐらいだし分類するほどでもないと思うけど

**Comment by denari** [comment]
なるほど。それよく見る気がするわ。thx

**Comment by denari** [comment]
https://kosen10s.doorkeeper.jp/events/42346
そこまで新参多くないっすね。いつもどおり。
であれば、とりあえずいつもどおりの ~~ガバガバ~~ ゆるゆるタイムスケジュールで良さそう。

悩みたくないのでcloseしま〜す。
