### ISSUE TITLE
当日の運営手伝いマンにやってもらうことをリスト化(シフト化??)

### ISSUE THREAD

**Issue by denari** [kosen10s/lt04docs#7]
毎回開始前がグダるから、今回あたりから受付とかの計画立てとこう

**Comment by denari** [comment]
ゴミの量減らしたいから、ゴミ箱ないで。ゴミは持ち帰ってや by会場

**Comment by denari** [comment]
@e10dokup : 買い出し仕切るマン ( #4 )

**Comment by c-bata** [comment]
なんか人足りてないところあれば言ってくれれば手伝います

**Comment by denari** [comment]
当日の(青少年利用のための)名簿に書いてない参加者が居た場合の受付時の対応をしないといけない。
わがままなタダの要望だけど、できれば俺はイベント会場側にいたいので誰かに頼もうと思っている。

ほかのタスクの整理のタイミングで各位に話をふるようにしようかな。

**Comment by denari** [comment]
@do-su-0805 : ゴミをよしなにする心の美しい人間 :+1:

**Comment by denari** [comment]
@e10dokup : 買い出し仕切るマン ( #4 )
@do-su-0805 : ゴミをよしなにする心の美しい人間
@denari : 集金

上記以外の人がやらないといけないこと
- 会場前で会場までの道順を案内するﾊﾟｰｿﾝ
- 買い出し手伝いﾋﾟｰﾎﾟｰ(2人)
- 会場設営ﾊﾟｰｿﾝ

多分これぐらいやろ。
特に事情がなければ、会場到着順で、上から順にタスク降る。
