### ISSUE TITLE
当日必要物品リストの作成

### ISSUE THREAD

**Issue by denari** [kosen10s/lt04docs#8]
https://nct-2010s.slack.com/archives/random/p1454049038000017 これつらかったからちゃんとしよう。

**Comment by denari** [comment]
プロジェクター : でなりが持参

**Comment by e10dokup** [comment]
ゴミ袋：そのへんで指定のものを買う

**Comment by do-su-0805** [comment]
前も書きましたが必要なものででかいものはあらかじめ僕んちまで送ってくれてかまいません。
住所は聞いてくれたら答えます。

ごみ袋に指定はありません。
天満は大阪市北区です。大阪市は中身が軽く見えるような袋であれば何でもかまいません。

ネットワークについては、ルータとスイッチは持参します。

**Comment by do-su-0805** [comment]
追記。
ごみについては僕んちまでもってきてくれれば捨てられます。（会場から二駅です
ついでに言うと前日とか、当日すぐに帰らない人は泊まってくれてかまいません。
前日は飲み会があるので遅くなります。

**Comment by denari** [comment]
# 持ってくるもの
- プロジェクター
- 名札ケース
- はさみ(持ってる人みんな持ってきてほしい)

# 買うもの
- 飲食
- 印刷した名札(安定と信頼のコンビニ印刷)
- ごみ袋

---

多分これでいけるハズ(突貫)

**Comment by denari** [comment]
上記でええやろ。closeしよう
